config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: "{{ env_var('MELTANO_ENVIRONMENT', 'dev') }}"
  outputs:
    dev:
      type: bigquery
      method: "{{ env_var('DBT_BIGQUERY_AUTH_METHOD') }}"
      project: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET') }}"
      threads: 2
      refresh_token: "{{ env_var('DBT_BIGQUERY_REFRESH_TOKEN', '') }}"
      client_id: "{{ env_var('DBT_BIGQUERY_CLIENT_ID', '') }}"
      client_secret: "{{ env_var('DBT_BIGQUERY_CLIENT_SECRET', '') }}"
      token_uri: "{{ env_var('DBT_BIGQUERY_TOKEN_URI', '') }}"
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE', '') }}"
    staging:
      type: bigquery
      method: "{{ env_var('DBT_BIGQUERY_METHOD') }}"
      project: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET') }}"
      threads: 4
      refresh_token: "{{ env_var('DBT_BIGQUERY_REFRESH_TOKEN', '') }}"
      client_id: "{{ env_var('DBT_BIGQUERY_CLIENT_ID', '') }}"
      client_secret: "{{ env_var('DBT_BIGQUERY_CLIENT_SECRET', '') }}"
      token_uri: "{{ env_var('DBT_BIGQUERY_TOKEN_URI', '') }}"
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE', '') }}"
    prod:
      type: bigquery
      method: "{{ env_var('DBT_BIGQUERY_METHOD') }}"
      project: "{{ env_var('DBT_BIGQUERY_PROJECT') }}"
      dataset: "{{ env_var('DBT_BIGQUERY_DATASET') }}"
      threads: 6
      refresh_token: "{{ env_var('DBT_BIGQUERY_REFRESH_TOKEN', '') }}"
      client_id: "{{ env_var('DBT_BIGQUERY_CLIENT_ID', '') }}"
      client_secret: "{{ env_var('DBT_BIGQUERY_CLIENT_SECRET', '') }}"
      token_uri: "{{ env_var('DBT_BIGQUERY_TOKEN_URI', '') }}"
      keyfile: "{{ env_var('DBT_BIGQUERY_KEYFILE', '') }}"
